- .prettierrc
- package.json
- src/controllers/todo.ts
- src/index.ts
- src/loaders/express.ts
- src/loaders/index.ts
- src/loaders/mongo.ts
- src/models/todo.ts
- src/routes/index.ts
- src/routes/todo.ts
- src/services/todo.ts
- tsconfig.json
- yarn.lock
- todo model 정의
- todo router 
- 
> feat: 데이터베이스 Todo 테이블 생성

- .prettierrc
- jest.config.js
- package.json
- src/index.ts
- tests/index.ts
- tests/setup.ts
- tsconfig.json
- yarn.lock
> chore: jest setting

- .eslintrc.json
- .husky/pre-commit
- package.json
- yarn.lock
> chore: husky setting

- README.md
> 프로젝트 설정 및 실행법 추가

- src/models/todo.ts
> feat: create todo table

- src/controllers/todo.ts
- src/index.ts
- src/loaders/express.ts
- src/loaders/index.ts
- src/loaders/mongo.ts
- src/routes/index.ts
- src/routes/todo.ts
- src/services/todo.ts
> feat: Todo 생성 api 추가

- package.json
- src/controllers/area.ts
- src/controllers/header.ts
- src/controllers/project.ts
- src/controllers/todo.ts
- src/index.ts
- src/loaders/express.ts
- src/loaders/index.ts
- src/loaders/mongo.ts
- src/models/area.ts
- src/models/header.ts
- src/models/project.ts
- src/models/todo.ts
- src/routes/area.ts
- src/routes/header.ts
- src/routes/index.ts
- src/routes/project.ts
- src/routes/todo.ts
- src/services/area.ts
- src/services/header.ts
- src/services/project.ts
- src/services/todo.ts
- yarn.lock
> feat: 데이터 베이스 설계 및 기본 Controller, Service 

- package.json
- src/loaders/express.ts
- yarn.lock
> fix: cors 에러

- .husky/pre-commit
- package.json
> fix: husky setting

- src/controllers/todo.ts
- src/routes/todo.ts
- src/services/todo.ts
- delete todo service
- delete todo controller
- delete todo router
- 페어 프로그래밍으로 작성
> feat:데이터베이스에서 요청된 할 일 삭제

- src/services/todo.ts
- 업무에 대한 설명
- 연관된 이슈
- 페어프로그래밍으로 진행하였습니다.
> fix: delete todo api

- .eslintrc.json
- .github/workflows/ci.yml
- jest.config.js
- package.json
- src/controllers/area.ts
- tsconfig.json
> feat: continuous integration

- src/controllers/area.ts
- src/controllers/header.ts
- src/controllers/project.ts
- src/controllers/todo.ts
- src/loaders/express.ts
- src/routes/area.ts
- src/routes/header.ts
- src/routes/project.ts
- src/utils/asyncHandler.ts
컨트롤러에서 try catch문을 생략하기 위해 asyncHandler 함수를 적용
> feat: asyncHandler 적용 및 에러처리

- appspec.yml
- src/controllers/area.ts
- src/controllers/header.ts
- src/controllers/project.ts
- src/controllers/todo.ts
- src/loaders/express.ts
- src/routes/area.ts
- src/routes/header.ts
- src/routes/project.ts
- src/utils/asyncHandler.ts
AWS codedeploy를 위한 appspec 파일 추가
> Continuous Deployment

- .gitignore
- package.json
- tsconfig.json
> chore: start script 추가

- appspec.yml
- scripts/application_stop.sh
- scripts/before_install.sh
- scripts/start.sh
> chore: add scripts

- src/loaders/express.ts
index 페이지에 방문시 hello mozi로 응답합니다.
https://mozi-server.com
> chore: / -> hello mozi로 응답

- package.json
- yarn.lock
> chore: nodemon devdependency 추가

- src/models/area.ts
- src/models/header.ts
- src/models/project.ts
- src/models/todo.ts
모델에 timestamp 옵션추가 -> createdAt, updatedAt 추가.
> refactor: model들 timestamp 추가

- src/loaders/mongo.ts
mongoose connection error시 수행할 작업 추가
> feat: mongoose connection err 추가

- src/models/todo.ts
> fix: todo return type

- src/services/todo.ts
- src/utils/serialize.ts
geoJson module화 작업 및 업데이트 로직 변경
현재 서버에서 location 데이터를 어떻게 업데이트 해줘야하나... 프론트에서 GeoJson 포맷에 맞게 변경해서 보내줘야하나 고민하다가 그냥 서버 코드 리팩토링함 (create 할때는 서버에서 GeoJson으로 만들어주는데 update 할때만 프론트에서 해주는게 말이안되기 때문에)
- longitude, latitude 들어오면 GeoJson 형식으로 시리얼라이즈 해주는 함수 생성
- update API에 longitude, latitude 들어오면 해당 함수를 사용하여 update 진행
> refactor: location update를 위한 GeoJson 모듈 생성

- .eslintrc.json
- package.json
- public/client.js
- public/index.html
- public/worker.js
- src/index.ts
- src/loaders/express.ts
- src/routes/index.ts
- src/routes/webpush.ts
- yarn.lock
튜토리얼을 따라 webpush 기본 기능을 구현했습니다.
> feat: webpush 기본 기능 구현

- package.json
- src/loaders/express.ts
- swagger.yaml
- yarn.lock
> Swagger 적용

- src/models/user.ts
로그인 기능을 구현하기 위해 우선 사용자의 정보를 DB에 저장해야합니다. 이를 위해서 User 스키마를 정의하겠습니다. 
카카오 로그인만을 염두에 뒀습니다. 그래서 카카오 인증 과정을 통해 얻을 수 있는 email만 사용해서 다음과 같이 정의하겠습니다.
```Typescript
type User = {
email: string
};
```
- User Schema 정의
이제 Todo Schema에서 이 Todo를 가지고 있는 User Id (MongoDB ObjectId)를 정의해주면 되는데, 생각해보니 Todo의 정보만 가지고 화면에 보이는 Todo의 순서는 어떻게 정해지나요?
> feat: User schema 정의

- src/loaders/express.ts
> chore: cors option credentials off

- src/controllers/todo.ts
- src/services/todo.ts
0개의 Todo를 찾았을 때 텅빈 배열을 반환하는데 Todo를 찾지못하면 null을 반환하게 했습니다.
> fix: findAllTodo (if empty return null)

- swagger.yaml
Response에 Done과 Description 타입 추가
> Swagger 문서 업데이트

- src/controllers/todo.ts
> fix: delete todo handler

- src/services/todo.ts
기존에는 업데이트 이전값반환 -> 업데이트 이후 값을 반환한도록 수정 (todo)
> fix: update todo 업데이트 된 값 반환

- src/config/index.ts
- src/loaders/mongo.ts
> chore: mongodb config (url)

- .github/workflows/ci.yml
- src/models/todo.ts
alarmed이 추가되어있지 않아서 빌드 에러 발생. 해당 프로퍼티를
추가합니다.
> chore: Todo 인터페이스 타입 에러 수정

- src/models/todo.ts
> feat: todo done column -> default false로 지정

- README.md
- package.json
- src/index.ts
- src/loaders/mongo.ts
- src/utils/logger.ts
- yarn.lock
> feat: pino logger

- src/controllers/location.ts
- src/routes/location.ts
- src/services/location.ts
> feat: get todos with location (service, router, controller)

- src/models/todo.ts
> feat: Todo 테이블에 soft_deleted 필드 추가

- src/controllers/auth.ts
- src/models/todo.ts
> feat: Todo Model에 pk 추가

- src/middlewares/auth.ts
- src/types/index.d.ts
- src/types/user.ts
- tsconfig.json
- yarn.lock
token인증을 확인하는 middleware를 만들었습니다.
> feat: jwt token verify middleware

- package.json
- src/services/todo.ts
- yarn.lock
Todo 생성시 uuid로 id를 만듭니다.
- uuid
```ts
export const createTodo = async (todo: any) => {
const newTodo = await Todo.create({ ...todo, id: uuid() });
return newTodo;
};
```
> feat: Todo 생성시 uuid로 id 만들기

- package.json
- src/controllers/auth.ts
- src/controllers/todo.ts
- src/middlewares/auth.ts
- src/routes/index.ts
- src/services/todo.ts
- src/types/index.d.ts
- tsconfig.json
로그인 했을 때 자신의 아이디로 자신의 Todo를 가져오는 작업을 수행합니다.
자신의 id로 Todo를 생성하고 자신의 Id의 Todo만 리스트뷰로 보여줍니다.
> feat: getAllTodos, createTodo에 protect middleware  적용해서 로그인 테스트

- src/controllers/todo.ts
- src/middlewares/auth.ts
- src/routes/todo.ts
- src/services/todo.ts
- src/types/user.ts
> feat: ownerId를 통한 Todo 전부 삭제 api

- src/models/todo.ts
> feat: Todo model index 컬럼 추가

- src/loaders/express.ts
cors 설정 추가했습니다.
도메인 vercel, mozi.cz 추가
> chore: cors 설정 추가

- src/controllers/auth.ts
> fix: cookie 저장 방법 수정

- src/models/index.ts
- src/models/todo.ts
리스트에서 todo의 순서를 바꿀 수 있도록 todo에 index 필드 추가
- todo class에 index 필드 추가 
- todo orm initializer에 index 필드 추가
todo 스키마가 바뀔 때 마다 기존의 테이블을 날려버려야 오류가 발생하지 않습니다.
> feat: todo index field added

- src/services/todo.ts
todo servcie에서 todo update 하는 방법 리팩토링.
> refactor: todo update service

- .dockerignore
- .github/workflows/cd.yml
- .gitignore
- Dockerfile
- docker-compose.yml
- init-letsencrypt.sh
- nginx/nginx.conf
- package.json
- src/loaders/sequelize.ts
- src/models/index.ts
backend dockerizing 및 github action을 사용한 CI/CD을 구현 하였습니다.
현재 kakao login redirect URL이 이상한지 자꾸 localhost로 리다이렉트 됩니다...
> feat: docker compose node nginx mysql & CI/CD

- package.json
- src/controllers/todo.ts
- src/types/express.d.ts
- src/types/index.d.ts
- src/types/user.ts
TS Compiler 오류 때문에 기존의 Request 타입을 확장해서 새로 정의했습니다.
- `types/express.d.ts` 추가
> feat: Express.Request.user defined

- swagger.yaml
별도의 api 문서를 만들지 않고 자동화하는데에 실패해서 수동으로 업데이트했습니다.
- api 문서 업데이트
> feat: api document updated

- src/middlewares/auth.ts
- src/routes/todo.ts
- src/services/todo.ts
쿼리에 paranoid option을 추가했습니다. 이 옵션을 켜야만 deletedAt 컬럼을 조회할 수 있습니다. (soft deleted 된 컬럼)
> feat: db 쿼리에 paranoid option 추가

- src/middlewares/auth.ts
- src/models/index.ts
- src/models/todo.ts
- src/services/todo.ts
Todo 스키마에 locationName이라는 필드를 추가했습니다.
- Todo 스키마에 locationName이라는 필드를 추가
> feat: todo schema locationName added

- swagger.yaml
`Todo` 스키마에 `locationName`이 추가되어서 api 문서를 업데이트했습니다.
- api 문서 업데이트
> feat: api docs updated

- src/services/todo.ts
모든 Todo를 삭제할 때 force 옵션을 줘서 deletedAt 컬럼을 삭제할 수 있도록 수정했습니다.
> fix: deleteAll force option

- src/controllers/todo.ts
- src/routes/todo.ts
- src/services/todo.ts
> feat: force Delete Todo

- package.json
- src/index.ts
- src/loaders/routes.ts
- yarn.lock
> feat: Sentry Error monitoring

- src/controllers/todo.ts
- src/routes/todo.ts
> feat: sync controller, router
